const { MessageEmbed } = require("discord.js-12");
const config = require("../../botconfig/config.json");
const ee = require("../../botconfig/embed.json");
const Discord = require("discord.js-12");
module.exports = {
  name: "additem",
  category: "👑 Market",
  aliases: ["addi"],
  cooldown: 7,
  usage: "additem <quantité> <prix> <item>",
  description: "Permet d'ajouter un item au market inter-serveurs",
  memberpermissions: [],
  requiredroles: [],
  alloweduserids: [],
  run: (client, message, prefix) => {
    const db = require("quick.db");
    var word_finder = require("close-word");

    let args = message.content.substring(prefix.length).split(" ");
    let args1 = message.content.split(" ").slice(3).join(" ");
    let items = db.get(`bot.items`);
    let itemsnbrs = db.get(message.author.id + ".itemsbnr");
    let newitems = Object.entries(items);

    let lastid = newitems.length;
    let author_id = message.author.id;

    if (!args[1])
      return message.channel.send(
        "Arguments invalide (" + prefix + "additem <quantité> <prix> <nom>)"
      );
    if (!isNumeric(args[1]))
      return message.channel.send(
        "Veuillez préciser un nombre valide pour la quantité !"
      );
    if (args[1] > 20000)
      return message.channel.send(
        "Veuillez préciser une quantité inférieur à 20 000"
      );
    if (args[1] < 1)
      return message.channel.send(
        "Veuillez préciser une quantité suppérieur à 1"
      );
    if (!args[2])
      return message.channel.send(
        "Arguments invalide (" + prefix + "additem <quantité> <prix> <nom>)"
      );
    if (args[2].length > 7)
      return message.channel.send(
        "Veuillez préciser un prix d'item moins long"
      );
    if (!isNumeric(args[2]))
      return message.channel.send(
        "Veuillez préciser un nombre valide pour le prix !"
      );
    if (args[2] < 1)
      return message.channel.send(
        "Veuillez préciser un nombre plus grande que 1$ !"
      );
    if (!args1)
      return message.channel.send(
        "Arguments invalide (" + prefix + "additem <quantité> <prix> <nom>)"
      );
    if (itemsnbrs > 4)
      return message.channel.send(
        "Vous avez atteint le nombre d'item maximal dans le market !"
      );

    var result = word_finder.findClosestOne(args1, [
      "roche",
      "bloc d'herbe",
      "terre",
      "podzol",
      "pierres",
      "planches de chêne",
      "planches de sapin",
      "planches de bouleau",
      "planches d'acajou",
      "planches d'acacia",
      "planches de chêne noir",
      "pousse de chêne",
      "pousse de sapin",
      "pousse de bouleau",
      "pousse d'acajou",
      "pousse d'acacia",
      "pousse de chêne noir",
      "sable",
      "sable rouge",
      "gravier",
      "minerai d'or",
      "minerai de fer",
      "minerai de charbon",
      "bois de chêne",
      "bois de sapin",
      "bois de bouleau",
      "bois d'acajou",
      "feuilles de chêne",
      "feuilles de sapin",
      "feuilles de bouleau",
      "feuilles d'acajou",
      "éponge",
      "verre",
      "minerai de lapis-lazuli",
      "bloc de lapis-lazuli",
      "distributeur",
      "grès",
      "grès sculpté",
      "grès poli",
      "bloc musical",
      "rails de propulsion",
      "rails détécteurs",
      "piston collant",
      "toile d'araignée",
      "hautes herbes",
      "fougère",
      "arbustre mort",
      "piston",
      "laine blanche",
      "laine orange",
      "laine magenta",
      "laine bleu clair",
      "laine jaune",
      "laine vert clair",
      "laine rose",
      "laine grise",
      "laine gris clair",
      "laine cyan",
      "laine violette",
      "laine bleue",
      "laine marron",
      "laine verte",
      "laine rouge",
      "laine noire",
      "pissenlit",
      "coquelicot",
      "orchidée bleue",
      "allium",
      "houstonie",
      "tulipe rouge",
      "tulipe orange",
      "tulipe blanche",
      "tulipe rose",
      "marguerite",
      "champignon",
      "bloc d'or",
      "bloc de fer",
      "dalle en pierre",
      "dalle en grès",
      "dalle en pierres",
      "dalle en brique",
      "dalle en pierre taillée",
      "dalle en briques du nether",
      "dalle en quartz",
      "briques",
      "tnt",
      "bibliothèque",
      "pierres moussues",
      "obsidienne",
      "torche",
      "escaliers en bois",
      "coffre",
      "minerai de diamand",
      "bloc de diamand",
      "établi",
      "terre labourée",
      "fourneau",
      "échelle",
      "rails",
      "escaliers en pierre",
      "levier",
      "plaque de pression",
      "minerai de redstone",
      "torche de redstone",
      "bouton",
      "neige",
      "glace",
      "cactus",
      "argile",
      "jukebox",
      "barrière",
      "citrouille",
      "roche du nether",
      "sable des âmes",
      "pierre lumineuse",
      "citrouille-lanterne",
      "verre blanc",
      "verre orange",
      "verre magenta",
      "verre bleu clair",
      "verre jaune ",
      "verre vert clair",
      "verre rose",
      "verre gris",
      "verre gris clair",
      "verre cyan",
      "verre violet",
      "verre bleu",
      "verre marron",
      "verre vert",
      "verre rouge",
      "verre noir",
      "trappe de bois",
      "barreaux de fer",
      "vitre",
      "pastèque",
      "lianes",
      "portillon",
      "escaliers en briques",
      "escaliers en pierre taillée",
      "mycélium",
      "nénuphar",
      "brique du nether",
      "barrière en briques du nether",
      "escaliers en briques du nether",
      "table d'enchantement",
      "lampe à redstone",
      "dalle en bois de chêne",
      "dalle en bois de sapin",
      "dalle en bois de bouleau",
      "dalle en bois d'acajou",
      "dalle en bois d'acacia",
      "dalle en bois de chêne noir",
      "escaliers en grès",
      "minerai d'émeraude",
      "coffre du néant",
      "crochet",
      "bloc d'émeraude",
      "escaliers en bois de sapin",
      "escaliers en bois de bouleau",
      "escaliers en bois d'acajou",
      "balise",
      "muret",
      "bouton",
      "enclume",
      "coffre piégé",
      "plaque de pression pondérée",
      "capteur de lumière du jour",
      "bloc de redstone",
      "minerai de quartz du nether",
      "entonnoir",
      "bloc de quartz",
      "escaliers en quartz",
      "rails déclencheurs",
      "dropper",
      "terre cuite blanche",
      "terre cuite orange",
      "terre cuite magenta",
      "terre cuite bleu clair",
      "terre cuite jaune",
      "terre cuite vert clair",
      "terre cuite rose",
      "terre cuite grise",
      "terre cuite gris clair",
      "terre cuite cyan",
      "terre cuite violette",
      "terre cuite bleue",
      "terre cuite marron",
      "terre cuite verte",
      "terre cuite rouge",
      "terre cuite noire",
      "vitre blanche",
      "vitre orange",
      "vitre magenta",
      "vitre bleu clair",
      "vitre jaune",
      "vitre vert clair",
      "vitre rose",
      "vitre grise",
      "vitre gris clair",
      "vitre cyan",
      "vitre violette",
      "vitre bleue",
      "vitre marron",
      "vitre verte",
      "vitre rouge",
      "vitre noire",
      "feuilles d'acacia",
      "feuilles de chêne noir",
      "bois d'acacia",
      "bois de chêne noir",
      "escaliers en bois d'acacia",
      "escaliers en bois de chêne noir",
      "bloc de paille",
      "tapis blanc",
      "tapis orange",
      "tapis magenta",
      "tapis bleu clair",
      "tapis jaune",
      "tapis vert clair",
      "tapis rose",
      "tapis gris",
      "tapis gris clair",
      "tapis cyan",
      "tapis violet",
      "tapis bleu",
      "tapis marron",
      "tapis vert",
      "tapis rouge",
      "tapis noir",
      "terre cuite",
      "bloc de charbon",
      "glace compactée",
      "tournesol",
      "lilas",
      "très hautes herbes",
      "grande fougère",
      "rosier",
      "pivoine",
      "pelle en fer",
      "pioche en fer",
      "hache en fer",
      "briquet",
      "pomme",
      "arc",
      "flèche",
      "charbon",
      "charbon de bois",
      "diamant",
      "lingot de fer",
      "lingot d'or",
      "épée en fer",
      "épée en bois",
      "pelle en bois",
      "pioche en bois",
      "hache en bois",
      "épée en pierre",
      "pelle en pierre",
      "pioche en pierre",
      "hache en pierre",
      "épée en diamant",
      "pelle en diamant",
      "pioche en diamant",
      "hache en diamant",
      "bâton",
      "bol",
      "soupe de champignons",
      "épée en or",
      "pelle en or",
      "pioche en or",
      "hache en or",
      "ficelle",
      "plume",
      "poudre à canon",
      "houe en bois",
      "houe en pierre",
      "houe en fer",
      "houe en diamant",
      "houe en or",
      "graines de blé",
      "blé",
      "pain",
      "chapeau en cuir",
      "tunique en cuir",
      "pantalon en cuir",
      "bottes en cuir",
      "casque en mailles",
      "cotte en mailles",
      "jambières en mailles",
      "bottes en mailles",
      "casque en fer",
      "plastron en fer",
      "jambières en fer",
      "bottes en fer",
      "casque en diamant",
      "plastron en diamant",
      "jambières en diamant",
      "bottes en diamant",
      "casque en or",
      "plastron en or",
      "jambières en or",
      "bottes en or",
      "silex",
      "viande de porc crue",
      "viande de porc cuite",
      "pomme dorée",
      "pomme cheat",
      "pancarte",
      "porte en bois",
      "sceau",
      "sceau d'eau",
      "sceau de lave",
      "porte en fer",
      "redstone",
      "bateau",
      "cuir",
      "sceau de lait",
      "brique",
      "argile",
      "canne à sucre",
      "papier",
      "livre",
      "boule de slime",
      "bousole",
      "canne à pêche",
      "poudre de pierre luisante",
      "poche d'encre",
      "rouge de rose",
      "vert de cactus",
      "fèves de cacao",
      "lapis-lazuli",
      "teinture violette",
      "teinture cyan",
      "teinture gris clair",
      "teinture grise",
      "teinture rose",
      "teinture magenta",
      "teinture orange",
      "poudre d'os",
      "os",
      "sucre",
      "gâteau",
      "lit",
      "carte",
      "cisailles",
      "pastèque",
      "graines de citrouille",
      "graines de pastèque",
      "boeuf cru",
      "steak",
      "poulet cru",
      "poulet rôti",
      "chair putréfiée",
      "enderpearl",
      "bâton de blaze",
      "larme de ghast",
      "pépite d'or",
      "verrue du nether",
      "oeil d'araignée",
      "oeil d'araignée fermenté",
      "poudre de blaze",
      "crème de magma",
      "alambic",
      "chaudron",
      "oeil du néant",
      "émeraude",
      "carotte",
      "pomme de terre",
      "pomme de terre cuite",
      "carte vierge",
      "carotte dorée",
      "crâne de squelette",
      "crâne de wither squelette",
      "tête de zombie",
      "tête",
      "tête de creeper",
      "étoile du nether",
      "fusée de feu d'artifice",
      "étoile de feu d'artifice",
      "brique du nether",
      "quartz du nether",
      "laisse",
      "étiquette",
      "coffre en fer",
      "coffre en or",
      "coffre en diamant",
      "coffre en cuivre",
      "coffre en argent",
      "coffre en ctristal",
      "coffre en obsidian",
      "Coffre en terre",
      "Amélioration coffre fer -> or",
      "Amélioration coffre or -> diamant",
      "Amélioration coffre cuivre -> argent",
      "Amélioration coffre argent -> or",
      "Amélioration coffre cuivre -> fer",
      "Amélioration coffre diamant -> crystal",
      "Amélioration coffre bois -> fer",
      "Amélioration coffre bois -> cuivre",
      "Amélioration coffre diamant -> obsidian",
      "Drawer 1x1",
      "Drawer 1x2",
      "Drawer 2x2",
      "Modèle d'amélioration",
      "Slimepad",
      "bloc de paladium",
      "bloc de titane",
      "bloc d'amethyst",
      "Four en paladium",
      "Spike en bois",
      "Spike en fer",
      "spiket en or",
      "spike en dimant",
      "spike en amethyst",
      "spike en titane",
      "spike en paladium",
      "rose",
      "Enclume",
      "Table d'enchantement",
      "balise",
      "glass",
      "Extractor",
      "Lucky block Paladium",
      "Lucky block endium",
      "Fleur de chasse",
      "ascenseur",
      "spawner vide",
      "spawner cassé",
      "poudre de perlinpinpin",
      "bambou",
      "bloc de bambou",
      "enclume en paladium",
      "Enclume en titane",
      "enclume en amethyst",
      "table d'écriture",
      "entonnoir en paladium",
      "bloc de trixium",
      "lingot d'amethyst",
      "lingot de titane",
      "lingot de paladium",
      "lingot d'endium",
      "fragment d'endium",
      "findium",
      "pépite d'endium",
      "pioche en amethyst",
      "pelle en amethyst",
      "hache en amethyst",
      "épée en amethyst",
      "casque en amethyst",
      "plastron en amethyst",
      "jambières en amethyst",
      "bottes en amethyst",
      "pioche titane",
      "hache en titane",
      "pelle en titane",
      "épée en titane",
      "casque en titane",
      "plastron en titane",
      "jambières en titane",
      "bottes en titane",
      "pioche en paladium",
      "hache en paladium",
      "pelle en paladium",
      "épée en paladium",
      "casque en paladium",
      "plastron en paladium",
      "jambières en paladium",
      "bottes en paladium",
      "pomme en paladium",
      "pioche en endium",
      "hache en endium",
      "pelle en endium",
      "épée en endium",
      "casque en endium",
      "plastron en endium",
      "jambières en endium",
      "bottes en endium",
      "chest explorer",
      "voidstone",
      "voidstone minage",
      "small ring",
      "medium ring",
      "big ring",
      "small endium ring",
      "medium endium ring",
      "big endium ring",
      "Heal Stick",
      "Speed stick",
      "Strength Stick",
      "jump stick",
      "stick of god",
      "damage stick",
      "hyper jump stick",
      "teleport stick",
      "unclaimfinder vert",
      "unclaimfinder orange",
      "unclaimfinder rouge",
      "unclaimfinder bleu",
      "paladium bow",
      "infernal knocker",
      "switch arrow",
      "orangeblue",
      "kiwano",
      "xp berry",
      "compressed xp berry",
      "orangeblue seeds",
      "kiwano seeds",
      "chervil seeds",
      "eggplants seeds",
      "furnace upgrade",
      "palamixed coal",
      "Empty bow modifier",
      "Bow range modifier",
      "bow speed modifier",
      "compressed paladium",
      "compressed titane",
      "compressed amethyst",
      "travel boots",
      "travel leggings",
      "hood helmer",
      "jump chestplate",
      "scuba helmet",
      "slimy helmet",
      "hang glider",
      "backpack",
      "magical tool",
      "endium gauntlet",
      "dynamite",
      "ninja dynamite",
      "big dynamite",
      "endium dynamite",
      "Sulfuric water",
      "Angelic water",
      "amethyst seedplanter",
      "titane seedplanter",
      "paladium seedplanter",
      "endium seedplanter",
      "stick paladium",
      "stick titane",
      "stick amethyst",
      "paladium core",
      "diamond string",
      "wing",
      "potion launcher",
      "legendarystone random",
      "legendarystone teleporation",
      "legendarystone invisibility",
      "legendarystone fortune",
      "legendarystone power",
      "legendarystone jobs",
      "legendarystone chaos",
      "extrapolated bucket",
      "axe patern",
      "hammer patern",
      "shovel patern",
      "broadsword patern",
      "fastsword patern",
      "pickaxe patern",
      "sword patern",
      "ingot patern",
      "block patern",
      "Socket patern",
      "fastsword head",
      "broadsword head",
      "pickaxe head",
      "sword head",
      "shovel head",
      "hammer head",
      "axe head",
      "smelt modifier",
      "fortune modifier",
      "speed modifier",
      "damage modifier",
      "flamme modifier",
      "knockback modifier",
      "autorepair modifier",
      "more upgrade modifier",
      "paladium hammer",
      "titane hammer",
      "amethyst hammer",
      "smith hammer",
      "paladium broadsword",
      "titane broadsword",
      "amethyst broadsword",
      "paladium fastsword",
      "titane fastsword",
      "amethyst fastsword",
      "colle",
      "moula stone",
      "Amélioration Cobblebreaker amethyst",
      "Amélioration Cobblebreaker titane",
      "Amélioration Cobblebreaker paladium",
      "aimant",
      "chorus fruit",
      "cooked mutton",
      "rabbit hide",
      "prismarine crystal",
      "prismarine shard",
      "beetroot",
      "beetroot seeds",
      "rabbit's foot",
      "raw mutton",
      "raw rabbit",
      "end crystal",
      "cooked rabbit",
      "obsdian",
      "connected dirt",
    ]);
    const add = new Discord.MessageEmbed()
      .setColor("EC5922")
      .setTitle("🔎 | Recherche Market")
      .setDescription("Item trouvé : `" + result.word + "`")
      .addField("Voulez-vous vraiment ajouter cette item ?", "✅ ou ❌")
      .setFooter(
        "© PalaBot 2021 • Created By Xvirus9",
        "https://cdn.discordapp.com/attachments/657878417324113983/873843137817239563/nT0fW4I-.jpg"
      );
    message.channel.send(add).then((m) => {
      m.react("✅");
      m.react("❌");
      const collector = m.createReactionCollector(
        (reaction, user) =>
          ["✅", "❌"].includes(reaction.emoji.name) && user.id === author_id,
        { time: 120000 }
      );

      collector.on("collect", (reaction) => {
        reaction.users.remove(author_id);
        if (reaction.emoji.name === "✅") {
          try {
            m.delete();
          } catch (e) {
            console.log(e);
          }
          items.unshift({
            name: result.word,
            price: args[2],
            nbr: args[1],
            id: lastid + 1,
            authorID: message.author.id,
          });

          db.set("bot.items", items);
          db.add(message.author.id + ".itemsbnr", 1);

          message.channel.send(
            "Vous venez d'ajouter `" +
              args[1] +
              "` " +
              result.word +
              " pour `" +
              args[2] +
              "$`"
          );
        } else {
          try {
            m.delete();
          } catch (e) {
            console.log(e);
          }
          message.channel.send("❌ Vente annulée...");
        }
      });
    });

    function isNumeric(str) {
      if (typeof str != "string") return false; // we only process strings!
      return (
        !isNaN(str) && !isNaN(parseFloat(str)) // use type coercion to parse the _entirety_ of the string (`parseFloat` alone does not do this)...
      ); // ...and ensure strings of whitespace fail
    }
  },
};
